# Generated by Django 2.2.19 on 2022-05-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Звучит круто!', verbose_name='Введите текст'),
        ),
    ]
